### ISSUE TITLE
How to force in this new structure

### ISSUE THREAD

**Issue by Gr-Nobel** [yazdipour/unlimited-ticktick-windows#11]
public DateTime? proEndDate
		{
			get
			{
				return new DateTime?(new DateTime(2042, 4, 2));
			}
			[CompilerGenerated]
			set
			{
				this.<proEndDate>k__BackingField = value;
			}
		}
		
		
		
		**Previously only get option worked. Now there is a set option.**
Cant find WPF.pro ........

Plz answer . did you faced some ligal issues or something?

**Comment by Gr-Nobel** [comment]
Was able to foce it.

**Comment by Gr-Nobel** [comment]
Now facing this following issue. when adding task throug quick add it throughs this error.



Operation System Version-> 10.0.22621.0 ***** 
CurrentTime -> 10/21/2023 17:42:01 ***** 
Locale -> en-US ***** 
Device Location -> en-US ***** 
Version ->  ***** 
Exception Type -> System.TypeLoadException ***** 
Exception Message -> Could not load type 'Invalid_Token.0x02000000' from assembly 'TickTick, Version=4.5.8.0, Culture=neutral, PublicKeyToken=null'. ***** 
Exception Data -> System.Collections.ListDictionaryInternal ***** 
 ->  ***** 
 -> TickTick ***** 
 -> Boolean IsTeamActive() ***** 
 ->    at ticktick_WPF.Util.UserManager.IsTeamActive()
   at ticktick_WPF.Cache.LimitCache.GetLimitByKey(LimitKind limit)
   at ticktick_WPF.Util.ProChecker.<CheckTaskLimit>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ticktick_WPF.Views.QuickAdd.QuickAddView.<DoAddTask>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ticktick_WPF.Views.QuickAdd.QuickAddWindow.<AddTask>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ticktick_WPF.Views.QuickAdd.QuickAddView.<OnEnterText>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) ***** ****

**Comment by yazdipour** [comment]
I just released the new version. Try that. If it didnt work, let us know

**Comment by Gr-Nobel** [comment]
it's working .
what changes did you made?

**Comment by yazdipour** [comment]
Nothing different really. UserModel is not changed and it has the same things.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
