### ISSUE TITLE
Program encounters an exception

### ISSUE THREAD

**Issue by nathmore** [yazdipour/unlimited-ticktick-windows#9]
![image](https://user-images.githubusercontent.com/127351726/223852649-29d95f98-851d-44bd-b842-fb098c897d41.png)

Operation System Version-> 10.0.22621.0 ***** 
CurrentTime -> 03/08/2023 22:59:31 ***** 
Locale -> en-US ***** 
Device Location -> en-US ***** 
Version -> 4.2.6.0 ***** 
Exception Type -> System.IO.FileLoadException ***** 
Exception Message -> Could not load file or assembly 'Ical.Net, Version=2.1.0.13691, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ***** 
Exception Data -> System.Collections.ListDictionaryInternal ***** 
 ->  ***** 
 -> TickTick ***** 
 -> Boolean IsHabitValidInToday(ticktick_WPF.Models.HabitModel, System.Collections.Generic.List`1[ticktick_WPF.Models.HabitCheckInModel]) ***** 
 ->    at ticktick_WPF.Views.Habit.HabitUtils.IsHabitValidInToday(HabitModel habit, List`1 checkIns)
   at ticktick_WPF.Service.Display.TaskDisplayService.<GetHabitsInToday>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ticktick_WPF.Service.Display.TaskDisplayService.<GetDisplayTaskInToday>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ticktick_WPF.Util.Provider.ProjectTaskDataProvider.<GetDisplayModels>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ticktick_WPF.Views.Widget.ProjectWidget.<>c__DisplayClass69_0.<<LoadTasks>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) ***** 

__________________________________________________________

(for context, my ticktick is in the spanish time zone and time formatting, if that matters, that window pops up right after I open the app) I could use some help, I don't really know a lot about programming, I've only made some courses of web development.

**Comment by satyamohlan** [comment]
Hi, I am also facing the same issue. My timezone is Indian so there's that.

**Comment by Gr-Nobel** [comment]
Now It's not working.
ticktick has changed the structure.
you have to install 4.2.3 version
